### ISSUE TITLE
rimworld每次启动后，改装武器参数错误，会丢失连射次数这个属性

### ISSUE THREAD

**Issue by KeeKalm** [RW-NodeTree/ModularizationVanillaWeapon#2]
游戏加载后改装武器参数错误，会丢失连射次数这个属性
![Snipaste_2023-01-09_11-51-04](https://user-images.githubusercontent.com/45805345/211238451-871e480c-5657-419f-9910-d0e7688fdca8.png)
[Player.log](https://github.com/RW-NodeTree/ModularizationVanillaWeapon/files/10370284/Player.log)

在重新改装武器后这个属性会恢复

和游戏性能相关的mod有
- Startup impact
- Dubs Performance Analyzer
- RuntimeGC
- RocketMan - Performance Mod

**Comment by c7246** [comment]
和Infusion这个mod有冲突吧,我去掉这个mod就没问题了
